### ISSUE TITLE
Is there a released version?

### ISSUE THREAD

**Issue by gdborton** [actions/add-to-project#15]
Hello I'm trying to test some automated workflows. I followed the README, but am seeing an issue:
> Error: Unable to resolve action `actions/add-to-project@v1`, unable to find version `v1`

I saw that the package.json contains '0.0.0' so I also tried that in place of v1, but then got:
> Error: Unable to resolve action `actions/add-to-project@v0.0.0`, unable to find version `v0.0.0`

2 related questions
- Is there a released version of this that is useable?
- If not, is there a package that GH recommends? for example I see this one in the market place
  - https://github.com/marketplace/actions/project-beta-automations

**Comment by jclem** [comment]
Hey @gdborton 👋 I have `v1` in the README which was just drafted for when we actually start publicizing and releasing this action.

For now, you can point to a branch name e.g. `actions/add-to-project@main` or a commit SHA e.g. `actions/add-to-project@62a16d0b8da8c8e8e5a07f780b4076d9b0398fe3`.

Let me know if that works!
