### ISSUE TITLE
Action is not working on Github enterpise 3.6

### ISSUE THREAD

**Issue by bdzanko17** [actions/add-to-project#214]
### Hello We are trying to use this action on github enterpise but having this error when I put URL of our domain. 
Invalid project URL:  https://OURDOMAIN/OURORG/OURREPO/projects/1. Project URL should match the format [https://github.com/<orgs-or-users>/<ownerName>/projects/<projectNumber]

<img width="881" alt="image" src="https://user-images.githubusercontent.com/41085720/190176319-5f3e0ed3-4fd6-48be-8a8e-b64920273d1d.png">
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/41085720/190176137-6264209c-3353-400c-ad23-b8d888bdf63a.png">

**Comment by jayspadie** [comment]
Hi @bdzanko17 .  The `add-to-project` action applies to the newer [GitHub Projects](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects), not [GitHub Projects (classic)](https://docs.github.com/en/issues/organizing-your-work-with-project-boards).  GitHub Projects are not available on GHES 3.6, but will be coming to GHES in the future.
