### ISSUE TITLE
Do we have to replace `RELEASE_VERSION` ?

### ISSUE THREAD

**Issue by mesqueeb** [actions/add-to-project#239]
with
```
- uses: actions/add-to-project@RELEASE_VERSION
```
do we have to replace `RELEASE_VERSION` with anything?

**Comment by mattcosta7** [comment]
> do we have to replace `RELEASE_VERSION` with anything?

You'd want to replace this most likely with the version tag or commit sha, so that you get a consistent version of this action when you run it (without the `@<version>` you'll always get a version from main, which could at at some point contain breaking changes).
