### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by tjoyal** [actions/add-to-project#257]
This warning was fixed in https://github.com/actions/add-to-project/pull/231. It is not present in the latest release which is v0.3.0.

<img width="1527" alt="Screenshot 2022-11-09 at 4 00 37 PM" src="https://user-images.githubusercontent.com/207902/200940784-b050158f-cf62-4733-a569-e3b7074d5d85.png">

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

Would we consider a version bump due to the importance of said change?

Alternatively for those looking for a quick way out: `uses: actions/add-to-project@51e172a520b4925f1909cbd44f0e991607db88a9`

**Comment by mattcosta7** [comment]
We've released [v0.4.0](https://github.com/actions/add-to-project/releases/tag/v0.4.0) which contains the updates from that sha!
