### ISSUE TITLE
main/v0.5.0: Could not resolve to a ProjectV2 with the number

### ISSUE THREAD

**Issue by ssbarnea** [actions/add-to-project#462]
Apparently this action does not work and gives and error about failure to find the project.
```
Could not resolve to a ProjectV2 with the number
```
I tried to use both latest release `@v0.5.0` and `@main` but the result was the same.

I know that the token is good because it used in another action that is called before this one.

![](https://sbarnea.com/ss/Screen-Shot-2023-09-08-14-03-59.53.png)

https://github.com/ansible/devtools/actions/runs/6121911508/job/16616619759?pr=132

I might be missing something but I also know that https://github.com/orgs/ansible/projects/86 is a valid project too. 

The workflow source is at https://github.com/ansible/devtools/blob/main/.github/workflows/ack.yml#L52-L58

**Comment by ssbarnea** [comment]
I wonder if extra permissions as described on https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs are needed. Still, the only permission that looks related is named `repository-projects: read|write|none` but to my knowledge these projects are organization level not project level.

**Comment by mattcosta7** [comment]
> @mattcosta7 I wonder if extra permissions as described on https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs are needed. Still, the only permission that looks related is named `repository-projects: read|write|none` but to my knowledge these projects are organization level not project level.
> 
> Maybe using the implicit token does not allow this and it would only work with a personal token.

Not near a computer for a bit, but are you using a legacy personal access token, or an action token?

Due to the graphql API backing this if I recall correctly, a personal access token is required

**Comment by mattcosta7** [comment]
github-token (required) is a personal access token with repo and project scopes. See Creating a PAT and adding it to your repository for more details


From the readme, details on that token setup

**Comment by ssbarnea** [comment]
Thanks, I can confirm that this is true. I will try to make a PR to mention not to attempt to use non PATs as they will not work.
