### ISSUE TITLE
Unable to resolve action `actions/add-to-project@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by muhlemmer** [actions/add-to-project#540]
After we merged a [dependabot PR](https://github.com/zitadel/oidc/pull/575) that upgrades this this action, the action runner fails with:

> Unable to resolve action `actions/add-to-project@v1`, unable to find version `v1`

Log of failed run: https://github.com/zitadel/oidc/actions/runs/8535894709/job/23383365622?pr=577

Did dependabot do the wrong thing here, or is there something wrong with release publishing to the marketplace?

**Comment by muhlemmer** [comment]
Apologies, just found out that my colleague changed the version in the dependabot PR. But as there is no dedicated `v1` release branch, `v1` won't work. Will revert to `v1.0.0` as proposed by dependabot initially.

**Comment by jpike88** [comment]
@skw super annoying and breaks the convention of other GitHub Actions, please fix this

**Comment by quantuminformation** [comment]
i get this Unable to resolve action
