### ISSUE TITLE
Could not resolve to a ProjectV2 with the number 3.

### ISSUE THREAD

**Issue by schmidtw** [actions/add-to-project#568]
This error message `Could not resolve to a ProjectV2 with the number 3.` is now being reported each time we run the `add-to-project` action using both `main` and `v1.0.1` versions.

![image](https://github.com/actions/add-to-project/assets/698825/d19e9a2b-97ca-4236-ae53-1142a1acf43c)

https://github.com/xmidt-org/xmidt-agent/actions/runs/9089359300/job/24980410591?pr=123

I have confirmed that the PAT being used is not expired.

**Comment by schmidtw** [comment]
This seems related to #411 and #462.

This workflow appears to have stopped working about 5 days ago: https://github.com/xmidt-org/xmidt-agent/actions/workflows/proj-xmidt-team.yml without any changes to the PAT & the PAT hasn't expired.

**Comment by keikoro** [comment]
The earliest failures of your workflow were caused by an account suspension. I'd follow up on that on/would assume the later ones are a hangover of that.

**Comment by schmidtw** [comment]
Yes, we had an issue with a suspended user.  We thought we fixed the problem, but apparently there are gremlins.  I'll re-review.  Thank you for your help!
